### ISSUE TITLE
targets in maximum coverage problems [feature-request] 

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#13]
Hi,

I was thinking it would be great to have targets in the maximum coverage formulation. 

Below is an example of a problem matrix generated for this formulation using targets. In this example we have four planning units (P1, P2, P3, and P4) and two features (F1, and F2). F1 is found in P1, P2, and P3, with the following abundances: 2, 1, 1. F2 is found in P2, P3, and P4 with the following  abundances: 10, 10, 10. The planning units P1, P2, P3, and P4 have the following costs: 2, 1, 1, and 1. The target for F1 is set to 2 (T1) and the target for F2 is set to 10 (T2). Finally, the budget is set to 2.

|P1  |P2 |P3 |P4  |F1  |F2  |rhs   |description          |
|:---|:--|:--|:---|:---|:---|:-----|:--------------------|
|0   |0  |0  |0   |1   |1   |    |max(obj)           |
|2   |1  |1  |  |-T1 |  |>=0 |F1 constraints     |
|  |10 |10 |10  |  |-T2 |>=0 |F2 constraints     |
|2   |1  |1  |1   |  |  |<=2 |budget constraints |
|B   |B  |B  |B   |B   |B   |    |variable types      |

In this example, the optimal solution meets targets for both species, by selecting the planning units P2 and P3.

If we set the budget to 1, then we could only meet the target for the F2. This could be achieved  by selecting any of P2, P3, or P4.

I'm part way through implementing this (in the jeffreyhanson/feature/maxcover-targets branch), but I thought it would be useful to document this here. Also,  let me know if you have any suggestions, so I can implement them before the PR.

For instance, here we have equal weights for the features (the 1's in the objective function), but we could potentially add weights (similar to Zonation) - do you think this is worth including?

Cheers,

Jeff

**Comment by mstrimas** [comment]
Interesting, sort of a hybrid between minsetcover and maxcoverage problems. Essentially solves the problem: maximize representation subject to both meeting the targets and staying within budget. I think this would be very useful.

I'd vote for not worrying about weights for now to keep things simple. Can always add them later. Also, I'd have the targets default to 0 so the problem simplifies to the standard maximum coverage problem if targets aren't provided.

**Comment by mstrimas** [comment]
Also, in this case I don't think it will be possible to ensure in advance that the problem is feasible. So we'll have to check based on the output of the solvers and notify the user that no solution was found.

**Comment by jeffreyhanson** [comment]
I don't think feasibility will be an issue. The problem aims to maximize the number of targets met wile only being constrained by the budget. 

If the budget is too low then the solution containing no planning units is optimal and feasible. 

If the targets are too high such that none can be met, then all solutions that contain a combination of planning units that do not exceed the budget are optimal.

If you like I can add these scenarios to the unit tests to verify this behavior?

**Comment by jeffreyhanson** [comment]
It occurs to met, if we gave the planning units a really small cost (eg. 0.000001), then in scenarios where there are multiple solutions that meet the targets that are less then the budget, we could use this to obtain the cheapest solution -- thoughts?

**Comment by mstrimas** [comment]
Looking at the code, I realize now I misunderstood what you were proposing. Given that the problem doesn't reduce to the original maximum coverage problem, instead of modifying the `maxcover_model` I've put into into a new model instead, which I've called `maxtargets_model`. The maxtargets branch contains this change in addition to updates to the docs, tests, and vignette. How does this sound to you? If you're on board I'll merge the changes.

In addition, since there will likely be many feasible solutions with the same objective function value, I think you're right about coming up with some way of distinguishing between cases and minimizing cost seems like a good option. My thought was to divide the cost vector to the total cost, then multiple by some small number to ensure that a cheaper solution will never override a target, e.g.
`cost <- 0.01 * cost / sum(cost) `. Thoughts?

**Comment by jeffreyhanson** [comment]
Sure that sounds great. Yeah, I like the idea of scaling the costs.
