### ISSUE TITLE
Add tests with testthat

### ISSUE THREAD

**Issue by mstrimas** [mstrimas/prioritizr#2]

**Comment by jeffreyhanson** [comment]
Hi,

Just letting you know, I'm going to start work on adding unit tests, and hopefully submit a PR later today.  

Cheers,

Jeff

**Comment by jeffreyhanson** [comment]
I've been adding tests in the feature/unit-tests branch. It's almost ready for a PR. I think I found a few things that are either "bugs" or "me not understanding what the correct output should be". So, I'll post another comment with the issues raised in the unit tests to double check this.

**Comment by mstrimas** [comment]
Cool, thanks for working on this

**Comment by jeffreyhanson** [comment]
Ok, here's a list of tests that are failing due to bugs or me expecting a different result. 

If you could respond to each item on this list and confirm if it is a bug or not that would be brilliant.

I'll update the tests accordingly, and then submit a PR for the unit tests. Then, I'll deal with any bugs raised by the tests in separate issues.

Cheers,

Jeff


### `df_to_matrix`
* If the user supplies a `data.frame` object with `NA` values in the `v` column this does not return an error. It returns a `simple_triplet_matrix` with an NA value.
```
df5 <- data.frame(i = c(1, 1, 3), j = c(1, 3, 3), v = c(10, 20, NA))
expect_error(df_to_matrix(df5))
```

### `calculate_boundaries`
* If the user supplies a `RasterLayer` object with `NA` values, the function returns a `data.frame` that still contains edges associated with the `NA` pixels.
```
r2 <- raster::raster(matrix(c(1:3, NA), 2, 2)) # raster with one NA value
s2 <- data.frame(
    i = c(1L,   1L,   1L,  2L,   2L,   3L,  3L),
    j = c(1L,   2L,   3L,  1L,   2L,   1L,  3L),
    v = c( 1,  0.5,  0.5,  0.5,  1.5,  0.5,  1.5))
b2 <- calculate_boundaries(r2, edge_factor=1)
expect_true(!4 %in% b2$i)
expect_true(!4 %in% b2$j)
expect_equal(data.frame(i=b2$i, j=b2$j, v=b2$v), s2)
```
* if the users supplies an infinite `edge_factor` the function does not return an error.
```
r1 <- raster::raster(matrix(1:16, 4, 4))
expect_error(calculate_boundaries(r1, edge_factor=Inf))
```

### `make_grid`
* If the user supplies a 16 cell `RasterLayer` object with an extents ranging from 0--1, and `cell_width` as 0.25 (the raster's resolution), I expect the function to return a `SpatialPolygons` object with 16 polygons with a bounding box matching that of the input `RasterLayer`.
```
rst <- raster::raster(matrix(1:16, 4, 4))
sp <- make_grid(rst, cell_width=res(rst)[1])
expect_length(sp@polygons, sum(!is.na(raster::as.matrix(rst))))
expect_equal(extent(sp@bbox), extent(rst))
```

### `maxcover_model`
* If the user supplies a buget that is less than the cost of any planning units, then no error (or warning) is returned.
```
cost <- 1:4
rij <- data.frame(feature=c(1L,1L,2L, 2L,2L), pu=c(1:2, 2:4), amount=c(1,1,10,10,10))
expect_error(maxcover_model(x=cost, rij=rij, budget=0.5)) # budget is too low
```
* If the user supplies a `SpatialPolygons` object to represent cost, then the `'cost'` element in the `maxcover_model` object is a `SpatialPolygons` object and not a `numeric` vector.
```
cost <- raster::rasterToPolygons(raster::raster(matrix(c(1:3, NA), ncol=2)))
names(cost) <- 'cost'
features1 <- raster::stack(raster::raster(matrix(c(1,1,0,0), ncol=2)),
raster::raster(matrix(c(0,10,10,10), ncol=2)))
expect_equal(maxcover_model(x=cost, features=features1, budget=5)$cost, 1:4)
```
* If the user supplies a `SpatialPolygons` object to represent cost with a NA value, then the `'included'` element of the `maxcover_model` object does not have a `FALSE` element.
```
cost <- raster::rasterToPolygons(raster::raster(matrix(c(1:3, NA), ncol=2)))
names(cost) <- 'cost'
features1 <- raster::stack(raster::raster(matrix(c(1,1,0,0), ncol=2)),
raster::raster(matrix(c(0,10,10,10), ncol=2)))
ms <- maxcover_model(x=cost, features=features1, targets=c(1,10),
target_type='absolute', budget=3.23)
expect_equal(ms$included, c(TRUE, TRUE, TRUE, FALSE))
```

**Comment by mstrimas** [comment]
**df_to_matrix**: I don't think NA values should necessarily raise an error here, since I can image a situation in which someone might want a matrix with NA elements. Not set on this though, so feel free to change if you feel strongly that this should be an error.

**calculate_boundaries**: This function isn't used at the moment. It was created in preparation for adding functions to solve Marxan-like problems with a boundary length term, however I never got around to that. In any case, since NA cells in the cost layer are meant to indicate planning units to exclude from the analysis, I agree that the boundaries should not be included for these cells. This will be a bit tricky because removing some cells will affect the edge boundaries of other cells. Also, yes, there probably should be a check for `is.finite(edge_factor)`.

**make_grid**: the grid extent will only match the input raster extent if `clip = TRUE`. Although a default of TRUE probably makes more sense, I put it to FALSE, because clipping takes a long time. You won't get 16 hexagons because (a) the hexagons don't exactly line up with the edges and (b) even if they did there will be additional pieces of hexagons filling the gaps.

```
rst <- raster::raster(matrix(1:16, 4, 4))
sp <- make_grid(rst, cell_width=res(rst)[1], clip = TRUE)
plot(rst)
plot(sp, add = TRUE)
```

### maxcover_model

- **Budget**: yes, this should likely return an error.
- **Cost**: yes, this is a bug. At the very end of maxcover_model.r, `cost = x[]` should likely be `cost = x$cost`.
- **NA cost**: my intention was for `included` to only apply to RasterLayer planning units. For SpatialPolygons, I assume that the user will only provide the polygons they want to consider as planning units. With that in mind, an error will be raised if any cost values are NA when a SpatialPolygons object is used. The reason you don't get this is because `rasterToPolygons()` drops cells with NA values, so you end up with a SPDF with only 3 features.

**Comment by jeffreyhanson** [comment]
### `df_to_matrix` 
* I think one of the advantages of using a sparse matrix object is to avoid representing cells with NAs in them to reduce the amount of memory used. This will be especially useful when working with large problems. So, what if we kept NA values in the argument to `v` as valid, but omitted these cells inside the `df_to_matrix` function, so that they are not present in the returned `simple_triplet_matrix`?

###  `calculate_boundaries`
* Yeah, it looks like modifying this to accommodate missing values will be rather tricky. Since it's not really used at the moment, would you mind if we dropped this function for the first CRAN release? Perhaps, if/when a later version is released that does BLM stuff, we can add it back in?

### `make_grid`
I agree that the `clip=FALSE` should be the default. Sorry, there was a typo in the example, and I meant to do square grids.
```
# make grids
rst <- raster::raster(matrix(1:16, 4, 4))
sp <- make_grid(rst, cell_width=raster::res(rst)[1], type='square')
# show plots 
sp::plot(sp, type='n')
raster::plot(rst, add=T)
sp::plot(sp, add=T)
# run comparisons
expect_length(sp@polygons, sum(!is.na(raster::as.matrix(rst))))
expect_equal(extent(sp@bbox), extent(rst))
```

### `maxcover_model`
Ok, yeah, that makes sense with the `NA` costs in `SpatialPolygons`. Sorry, I should have caught the omission caused by `rasterToPolygons`.

**Comment by jeffreyhanson** [comment]
As discussed in #26, I removed the `df_to_matrix`. 

If you could double check if the `make_grid` with squares behaves as expected that would be great, so then I can submit a PR for the unit tests. Since the grid cells have an equal width to the raster's resolution, I would have expected `make_grid` to be equivalent to `as(rst, 'SpatialPolygons')`?

**Comment by mstrimas** [comment]
Removing `calculate_boundaries` until it's required makes sense to me.

Regarding `make_grid`, the issue arises because the extent of the input object is buffered prior to being tessellated with squares or hexagons, otherwise the cells won't capture the edges of the study area. In the special case when the input is a raster object and a square grid with the same resolution is requested, the buffering results in the grids not aligning, which I agree doesn't make sense. 

One option to fix this, is to not buffer when the grid is square and the input is a RasterLayer. However, if the grid size doesn't match the raster resolution, this results in the grid not filling the study area, e.g.:

![mismatch](https://cloud.githubusercontent.com/assets/7296482/19930037/d7d1d1ce-a0dc-11e6-965e-35b2288c21aa.png)

Another option is increasing the size of the buffer so that the grid will align if it's the same resolution as the raster, however, this results in some cells that are totally outside of the study area because touching on an edge is considered intersecting by `rgeos::gIntersection()`:

![overlap](https://cloud.githubusercontent.com/assets/7296482/19930158/83e45982-a0dd-11e6-8c7b-b8e9458aab39.png)

of course, `clip = FALSE` will get rid of this.

The final option would be to single out this special case (the cell_width and raster resolution are equal) and only avoid the buffering for this case. This final one seems best to me. If you agree I'll push the change.

**Comment by mstrimas** [comment]
I just pushed a change that went with the final option in the previous comment. If the grid cell_width divides evenly into the raster resolution, then there will be no buffering and the grids will overlap nicely. All other cases are unaffected.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
